# Generated by Django 6.0.2 on 2026-02-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='base_fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='berth',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('CNF', 'Confirmed'), ('RAC', 'RAC'), ('WL', 'Waiting List'), ('CAN', 'Cancelled')], default='CNF', max_length=3),
        ),
        migrations.AddField(
            model_name='booking',
            name='coach',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='current_status',
            field=models.CharField(choices=[('CNF', 'Confirmed'), ('RAC', 'RAC'), ('WL', 'Waiting List'), ('CAN', 'Cancelled')], default='CNF', max_length=3),
        ),
        migrations.AddField(
            model_name='booking',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
       migrations.AddField(
    model_name="booking",
    name="pnr",
    field=models.CharField(blank=True, max_length=10, null=True, unique=True),
),
        migrations.AddField(
            model_name='booking',
            name='quota',
            field=models.CharField(choices=[('GN', 'General')], default='GN', max_length=3),
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
