# Generated by Django 6.0.2 on 2026-02-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0003_alter_booking_pnr_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pnr',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
