# Generated by Django 6.0.2 on 2026-03-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='booking_id_ref',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='dedupe_key',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='event_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
