# Generated by Django 6.0.2 on 2026-03-02 15:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0006_notification_booking_id_ref_notification_dedupe_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('receiver_name', models.CharField(blank=True, default='', max_length=120)),
                ('receiver_phone', models.CharField(blank=True, default='', max_length=30)),
                ('distance_km', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('DEPARTED', 'Departed'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='BOOKED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcel_from', to='railway.routestop')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_bookings', to='railway.trainservice')),
                ('to_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcel_to', to='railway.routestop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_bookings', to='railway.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
